on: [push]
jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and Set Up JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          echo "JMETER_HOME=$PWD/apache-jmeter-5.6.3" >> $GITHUB_ENV
          echo "$PWD/apache-jmeter-5.6.3/bin" >> $GITHUB_PATH

      - name: Install JMeter Custom Thread Groups Plugin
        run: |
          mkdir -p apache-jmeter-5.6.3/lib/ext
          curl -L -o apache-jmeter-5.6.3/lib/ext/jmeter-plugins-threads.jar \
            https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-threads/2.1/jmeter-plugins-threads-2.1.jar

      - name: Run JMeter Test
        run: |
          jmeter -n -t ReqRes-Test-Plan.jmx -l results.jtl -e -o html-report
